// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_cpp
void test_cpp();
RcppExport SEXP rc2016_test_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_cpp();
    return R_NilValue;
END_RCPP
}
