# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    .Call('testing_hello_world', PACKAGE = 'testing')
}

hello_world2 <- function(n) {
    .Call('testing_hello_world2', PACKAGE = 'testing', n)
}

hello_world3 <- function(n) {
    .Call('testing_hello_world3', PACKAGE = 'testing', n)
}

hello_world4 <- function(n) {
    .Call('testing_hello_world4', PACKAGE = 'testing', n)
}

pi_sample <- function(n) {
    .Call('testing_pi_sample', PACKAGE = 'testing', n)
}

update_model <- function(x, nr, nc) {
    .Call('testing_update_model', PACKAGE = 'testing', x, nr, nc)
}

update_model2 <- function(n, x, nr, nc) {
    .Call('testing_update_model2', PACKAGE = 'testing', n, x, nr, nc)
}

update_model3 <- function(n, x, nr, nc) {
    .Call('testing_update_model3', PACKAGE = 'testing', n, x, nr, nc)
}

universe_create <- function(x, nr, nc) {
    .Call('testing_universe_create', PACKAGE = 'testing', x, nr, nc)
}

universe_update <- function(obj) {
    invisible(.Call('testing_universe_update', PACKAGE = 'testing', obj))
}

universe_get <- function(obj) {
    .Call('testing_universe_get', PACKAGE = 'testing', obj)
}

